### ISSUE TITLE
Non registra transazione

### ISSUE THREAD

**Issue by KingKaitoKid** [AndryCola/tracciaFinanze#13]
Dati inseriti:
Valore: +20
Contante: si
Movimento passato: no
Nota: Promo 2 menu a 14 (McChicken e McCrispy) + 6 McNuggets e salsa
Esercente: McDonald's

Non registra perché la nota non viene accettata.

**Comment by AndryCola** [comment]
bug risolto nella versione 4.0 e forse anche nella 3.0
