### ISSUE TITLE
Modifica username non fa mostrare i conti

### ISSUE THREAD

**Issue by KingKaitoKid** [AndryCola/tracciaFinanze#14]
Modificando username dalle impostazioni del profilo nella home non mostra più alcun dato (né conti che sono aperti né nome del conto nella home)

![image](https://user-images.githubusercontent.com/28398955/102030290-7e74f800-3db2-11eb-9f38-3f290780cb1b.png)

**Comment by AndryCola** [comment]
bug risolto nella 4.0
