### ISSUE TITLE
Nelle impostazioni profilo la label va nella text box nonostante il testo ci sia

### ISSUE THREAD

**Issue by KingKaitoKid** [AndryCola/tracciaFinanze#15]
Quando una text box è vuota la label ha sembianze di un placeholder (testo fantasma quando l'area di testo è vuota), quando è nel focus l'area di testo questa label va nel bordo precisamente in alto a destra e togliendo il focus la label dovrebbe rimanere nel bordo invece finisce dentro l'area di testo come se fosse la placeholder e si va a sovrapporre con testo inserito. 

![image](https://user-images.githubusercontent.com/28398955/102030400-fa6f4000-3db2-11eb-8a9b-5a4a74ab276c.png)

**Comment by AndryCola** [comment]
risolto nella 4.0
