### ISSUE TITLE
Non accetta esercenti con apostrofi

### ISSUE THREAD

**Issue by KingKaitoKid** [AndryCola/tracciaFinanze#5]
Un esercente con l’apostrofo non viene accettato ed il movimento non viene registrato.
Il problema non si verifica invece con un movimento che ha un apostrofo tra le note.

La versione del sito di riferimento è quella su Altervista.

**Comment by KingKaitoKid** [comment]
Notta aggiuntiva: inserendo questo come nota il movimento non viene registrato.

Tutti i campi inseriti:
Valore: -14
Contante: Si
Nota: 2 menu large promo (chicken + crispy) e 6 McNuggets 
Esercente: McDonald

**Comment by AndryCola** [comment]
prendo subito in esame la tua richiesta

**Comment by AndryCola** [comment]
ho risolto il bug nella versione 3.1 che uscirà fra un po' di tempo
